CF = gcc -Wall -g -std=c99 -lm

default: all 

all:
	$(CF) q0.c -o q0
	$(CF) q1.c -o q1
	$(CF) q2.c -o q2
	$(CF) q3.c -o q3

q0: q0.c
	$(CF) q0.c -o q0

q1: q1.c
	$(CF) q1.c -o q1 

q2: q2.c
	$(CF) q2.c -o q2 

q3: q3.c
	$(CF) q3.c -o q3 

clean:
	rm *.o 

